### ISSUE TITLE
Time display disappears when sound control is turned off

### ISSUE THREAD

**Issue by BODZy** [Samillion/ModernZ#282] opened 2024-12-29 11:20 UTC
### Reproduction Steps

volume_control=no

### Expected Behavior

Time is displayed

### Actual Behavior

![Screenshot 2024-12-29 131532](https://github.com/user-attachments/assets/4173e225-2448-47e8-acef-a36bcb0b7035)

### I carefully read all instructions and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information.

**Comment by BODZy** [comment] 2024-12-29 11:22
![image](https://github.com/user-attachments/assets/efa243ea-44ad-45eb-a432-31ebeafee14d)
I use the volume control from uosc, so I turn off the volume control here

**Comment by Samillion** [comment] 2024-12-29 11:51
Noted. Should be fixed alongside #279 

Off topic:
That's an interesting implementation with uosc volume control. May I ask how you implemented it?

**Comment by BODZy** [comment] 2024-12-29 12:14
> Noted. Should be fixed alongside #279 (still in progress)
> 
> Off topic: That's an interesting implementation with uosc volume control. May I ask how you implemented it?
I just disabled the features I don't need and use the “frankenstein” of both

https://github.com/user-attachments/assets/6dacb599-0a83-4010-abe3-2eab52752df1

**Comment by Samillion** [comment] 2024-12-29 12:15
Sorry, I should have clarified. I meant how did you integrate uosc elements (code, script wise)

**Comment by BODZy** [comment] 2024-12-29 12:21
> Sorry, I should have clarified. I meant how did you integrate uosc elements (code, script wise)

I don't. UOSC allows you to disable unnecessary elements via config. “Contextual” menus added via modernz.conf 
![image](https://github.com/user-attachments/assets/191f8ff3-3fc9-4bbf-8cc6-ee0f96a02427)

**Comment by Samillion** [comment] 2024-12-29 12:57
Thank you for the report. Could you please test with this script and let me know the results?

**Test script:** [time_codes_visibility/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_timecodes_x_position/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/b6d859b757845d5854c5ae6921f3552847101fea

**Changes:**
- Don't hide time codes if `volume_control` is disabled
- Adjust time codes position correctly based on `volume_control`

**Comment by Samillion** [comment] 2024-12-29 13:06
Side note: Really love your invention of using both OSCs, next level comfort.

**Comment by BODZy** [comment] 2024-12-29 13:08
![image](https://github.com/user-attachments/assets/b9707570-3975-4338-ac99-a828aa9f9cfd)

**Comment by Samillion** [comment] 2024-12-29 13:09
Awesome. Please let me know if any hiccups occur. I'm honestly glad this was caught early on with the new design of OSC.

**Comment by BODZy** [comment] 2024-12-29 14:35
[portable_config.zip](https://github.com/user-attachments/files/18269894/portable_config.zip)
If anyone would like to try :>

**Comment by BODZy** [comment] 2024-12-29 14:38
I don't know if it's intentional or not, but if you press RMB on pin/unpin, the system frame appears and disappears only after restarting the MPV

**Comment by Samillion** [comment] 2024-12-29 14:50
> I don't know if it's intentional or not, but if you press RMB on pin/unpin, the system frame appears and disappears only after restarting the MPV

I'm unable to reproduce this behavior. Is it possible that something from uosc is conflicting?

**Comment by BODZy** [comment] 2024-12-29 14:55
> > I don't know if it's intentional or not, but if you press RMB on pin/unpin, the system frame appears and disappears only after restarting the MPV
> 
> I'm unable to reproduce this behavior. Is it possible that something from uosc is conflicting?

Same without any other scrips
![image](https://github.com/user-attachments/assets/d2431413-035f-4cf4-92e2-c47c85439a28)
![image](https://github.com/user-attachments/assets/c840ff7f-7dbc-43f3-9d5a-523963a5cc37)

**Comment by Samillion** [comment] 2024-12-29 14:58
Oh, you meant the native window border. Yes, that is intended behavior.

https://github.com/Samillion/ModernZ/blob/main/docs/CONTROLS.md#pin

In essence, right click does not hide native border, and restores it if it's not there. (`--border=yes`)

**Comment by BODZy** [comment] 2024-12-29 15:01
> Oh, you meant the native window border. Yes, that is intended behavior.
> 
> https://github.com/Samillion/ModernZ/blob/main/docs/CONTROLS.md#pin
> 
> In essence, right click does not hide native border, and restores it if it's not there. (`--border=yes`)

Ok, get it.
btw Is there any way to lock the UI and make it non-clickable so that when you pin it, it acts as some sort of Picture in a Picture?

**Comment by Samillion** [comment] 2024-12-29 15:03
I use this auto profile in `mpv.conf`, which essentially turns the pin button to PIP

```EditorConfig
[Window-PIP]
    profile-desc=On window pin resize and move window
    profile-cond=ontop and ontop == true and not fullscreen
    profile-restore=copy-equal
    geometry=100%:100%
    autofit=50%x40%
    autofit-larger=50%x40%
```

**Comment by Samillion** [comment] 2024-12-29 15:09
If you don't want the OSC to show at all during that mode, you can add this to it:
```EditorConfig
script-opts-append=modernz-visibility=never
```

Though you need to add a keybind in `input.conf` to toggle ontop behavior, since you won't have osc buttons anymore in PIP.

**Comment by BODZy** [comment] 2024-12-29 15:55
> If you don't want the OSC to show at all during that mode, you can add this to it:
> 
> ```editorconfig
> script-opts-append=modernz-visibility=never
> ```
> 
> Though you need to add a keybind in `input.conf` to toggle ontop behavior, since you won't have osc buttons anymore in PIP.

Thx, it worked! Now I just need to figure out how to hide UOSC elements.

**Closed** 2024-12-29 17:08 UTC
Labels: bug
