### ISSUE TITLE
bug/keeponpause not working

### ISSUE THREAD

**Issue by Anthonyy232** [Samillion/ModernZ#33] opened 2024-10-17 08:22 UTC
Hi, this setting doesn't seem to work. I believe the intended behavior is to enable or disable whether the OSC should hide after a certain number of ms when the video is paused. I've tried it on 'yes' and 'no', doesn't seem to work. The OSC doesn't disable.

keeponpause=yes

Config: https://pastebin.com/NVsGMprx

**Comment by Samillion** [comment] 2024-10-17 09:25
It works as intended, but I agree about the inconsistent behavior.

It implies that the OSC will never hide if video is paused, but this is not the case.

**Behavior**:
- On pause, OSC will remain shown unless mouse moves over within mpv window

**Comment by Samillion** [comment] 2024-10-17 09:50
Example of a paused video with `showonpause=yes`

https://github.com/user-attachments/assets/fd3bb1c6-fd7e-4974-ad3b-347c76fd9ea7

**Comment by Anthonyy232** [comment] 2024-10-17 19:02
Is there a way to enable the hide OSC after x time even when paused then?

**Comment by Samillion** [comment] 2024-10-17 19:42
Could you set both of these to yes and try, please:
```ini
showonpause=yes
keeponpause=yes
```

I now see how redundant to have two user options for this feature, as this is remnants of previous forks.

The first one "flashes show OSC", the other "keeps OSC showing until mouse move or no pause"

They should be combined into one. What do you think?

**Comment by Anthonyy232** [comment] 2024-10-17 19:52
When both are set to true, the behavior is: when paused, the OSC turns on, and does not fade away even after a couple seconds and moving the mouse to another screen.

I found my intended (sort of) behavior, and it is when showonpause=no and keeponpause=yes. This changes it so that the OSC fades if there is no mouse movement on the player even when paused. However, this does not work when the player is in full screen, and also the OSC does not show when paused -- only when there is mouse movement.

Ideally, the behavior of a setting like this would be: user is playing a video, then pauses the video player. The OSC turns on, and if there is no mouse movement on the player then the OSC should fade away.

I think it can be simplified for sure.

**Comment by Samillion** [comment] 2024-10-17 19:59
Agreed and noted. Will improve this soon.

> However, this does not work when the player is in full screen

The logic at the moment is:
```lua
    -- autohide
    if state.showtime ~= nil and get_hidetimeout() >= 0 then
        local timeout = state.showtime + (get_hidetimeout() / 1000) - now
        if timeout <= 0 and get_touchtimeout() <= 0 then
            if state.active_element == nil and (user_opts.bottomhover or not mouse_over_osc) then
                if not (state.paused and user_opts.keeponpause) then
                    hide_osc()
                end
            end
        else
```

and:
```lua
mp.observe_property("pause", "bool", function(name, enabled)
	pause_state(name, enabled)
	if user_opts.showonpause then
		if enabled then
			visibility_mode("always", true)
			show_osc()
		else
			visibility_mode("auto", true)
		end
	end
end)
```

Definitely needs tuning. Though the keyword here is tuning, finding the perfect balance that most users would want.

**Comment by Anthonyy232** [comment] 2024-10-17 21:40
Sure, I'm okay with most behaviors as long as there is a way to hide the OSC on pause eventually. This is useful for screenshotting or looking for a particular frame.

**Comment by Samillion** [comment] 2024-10-17 21:53
Agreed.

> This is useful for screenshotting or looking for a particular frame.

Not sure if you know, I've added the ability to add flags to the screenshot button:
```ini
# show screenshot button
showscreenshot=yes
# flag for the screenshot button. subtitles, video, window, each-frame
# https://mpv.io/manual/master/#command-interface-screenshot-%3Cflags%3E
screenshot_flag=subtitles
```

Which should help you take screenshots without the OSC, even if OSC is showing. (`subtitles`, `video`). I've set it to subtitles (no OSC, show subtitle) as that is the default behavior in mpv. You can change it to your liking.

`subtitles`, `video`, `window`, `each-frame`, `subtitles+each-frame`, `video+each-frame`, `window+each-frame`

> or looking for a particular frame

### Jump Back/Forward

| Action                           | Function                                                             |
|-------------------------|---------------------------------------------------|
| Shift+left mouse click    | Skips to the previous/next frame (and pauses)     |

**Comment by Anthonyy232** [comment] 2024-10-17 21:57
Thanks! It's a very useful option and I'm mildly aware of that. But sometimes I want to screenshot using flameshot or something and use the built in draw tool -- that's why this feature is useful for me.

**Comment by Samillion** [comment] 2024-10-21 00:28
I apologize for the delay, I've been traveling for a while, so on the road constantly. Now that I have some free time, I'll address this issue, if one exists.

> showonpause=no and keeponpause=yes

So this is ok now? Anything broken or needs adjusting code wise?

**Comment by Anthonyy232** [comment] 2024-10-21 00:44
If both are set to no, can the OSC hide after x amount of time if there is no mouse movement?

**Comment by Samillion** [comment] 2024-10-21 01:13
That should be the behavior with:
```editorconfig
showonpause=yes
keeponpause=no
```

I see the problem exactly now. Will release a fix in a moment.

**Comment by Samillion** [comment] 2024-10-21 01:22
Should be fixed in the latest update:
https://github.com/Samillion/ModernZ/blob/main/modernz.lua

**Closed** 2024-10-21 01:22 UTC
Labels: enhancement, priority:low
